from .e2Enum import E2Enum
import gi
gi.require_version('Atspi', '2.0')
from gi.repository import Atspi

class E2Role(E2Enum):
    INVALID = (hash(Atspi.Role(0)), Atspi.Role.get_name(Atspi.Role(0)))
    ACCELERATOR_LABEL = (hash(Atspi.Role(1)), Atspi.Role.get_name(Atspi.Role(1)))
    ALERT = (hash(Atspi.Role(2)), Atspi.Role.get_name(Atspi.Role(2)))
    ANIMATION = (hash(Atspi.Role(3)), Atspi.Role.get_name(Atspi.Role(3)))
    ARROW = (hash(Atspi.Role(4)), Atspi.Role.get_name(Atspi.Role(4)))
    CALENDAR = (hash(Atspi.Role(5)), Atspi.Role.get_name(Atspi.Role(5)))
    CANVAS = (hash(Atspi.Role(6)), Atspi.Role.get_name(Atspi.Role(6)))
    CHECK_BOX = (hash(Atspi.Role(7)), Atspi.Role.get_name(Atspi.Role(7)))
    CHECK_MENU_ITEM = (hash(Atspi.Role(8)), Atspi.Role.get_name(Atspi.Role(8)))
    COLOR_CHOOSER = (hash(Atspi.Role(9)), Atspi.Role.get_name(Atspi.Role(9)))

    COLUMN_HEADER = (hash(Atspi.Role(10)), Atspi.Role.get_name(Atspi.Role(10)))
    COMBO_BOX = (hash(Atspi.Role(11)), Atspi.Role.get_name(Atspi.Role(11)))
    DATE_EDITOR = (hash(Atspi.Role(12)), Atspi.Role.get_name(Atspi.Role(12)))
    DESKTOP_ICON = (hash(Atspi.Role(13)), Atspi.Role.get_name(Atspi.Role(13)))
    DESKTOP_FRAME = (hash(Atspi.Role(14)), Atspi.Role.get_name(Atspi.Role(14)))
    DIAL = (hash(Atspi.Role(15)), Atspi.Role.get_name(Atspi.Role(15)))
    DIALOG = (hash(Atspi.Role(16)), Atspi.Role.get_name(Atspi.Role(16)))
    DIRECTORY_PANE = (hash(Atspi.Role(17)), Atspi.Role.get_name(Atspi.Role(17)))
    DRAWING_AREA = (hash(Atspi.Role(18)), Atspi.Role.get_name(Atspi.Role(18)))
    FILE_CHOOSER = (hash(Atspi.Role(19)), Atspi.Role.get_name(Atspi.Role(19)))

    FILLER = (hash(Atspi.Role(20)), Atspi.Role.get_name(Atspi.Role(20)))
    FOCUS_TRAVERSABLE = (hash(Atspi.Role(21)), Atspi.Role.get_name(Atspi.Role(21)))
    FONT_CHOOSER = (hash(Atspi.Role(22)), Atspi.Role.get_name(Atspi.Role(22)))
    FRAME = (hash(Atspi.Role(23)), Atspi.Role.get_name(Atspi.Role(23)))
    GLASS_PANE = (hash(Atspi.Role(24)), Atspi.Role.get_name(Atspi.Role(24)))
    HTML_CONTAINER = (hash(Atspi.Role(25)), Atspi.Role.get_name(Atspi.Role(25)))
    ICON = (hash(Atspi.Role(26)), Atspi.Role.get_name(Atspi.Role(26)))
    IMAGE = (hash(Atspi.Role(27)), Atspi.Role.get_name(Atspi.Role(27)))
    INTERNAL_FRAME = (hash(Atspi.Role(28)), Atspi.Role.get_name(Atspi.Role(28)))
    LABEL = (hash(Atspi.Role(29)), Atspi.Role.get_name(Atspi.Role(29)))

    LAYERED_PANE = (hash(Atspi.Role(30)), Atspi.Role.get_name(Atspi.Role(30)))
    LIST = (hash(Atspi.Role(31)), Atspi.Role.get_name(Atspi.Role(31)))
    LIST_ITEM = (hash(Atspi.Role(32)), Atspi.Role.get_name(Atspi.Role(32)))
    MENU = (hash(Atspi.Role(33)), Atspi.Role.get_name(Atspi.Role(33)))
    MENU_BAR = (hash(Atspi.Role(34)), Atspi.Role.get_name(Atspi.Role(34)))
    MENU_ITEM = (hash(Atspi.Role(35)), Atspi.Role.get_name(Atspi.Role(35)))
    OPTION_PANE = (hash(Atspi.Role(36)), Atspi.Role.get_name(Atspi.Role(36)))
    PAGE_TAB = (hash(Atspi.Role(37)), Atspi.Role.get_name(Atspi.Role(37)))
    PAGE_TAB_LIST = (hash(Atspi.Role(38)), Atspi.Role.get_name(Atspi.Role(38)))
    PANEL = (hash(Atspi.Role(39)), Atspi.Role.get_name(Atspi.Role(39)))
    
    PASSWORD_TEXT = (hash(Atspi.Role(40)), Atspi.Role.get_name(Atspi.Role(40)))
    POPUP_MENU = (hash(Atspi.Role(41)), Atspi.Role.get_name(Atspi.Role(41)))
    PROGRESS_BAR = (hash(Atspi.Role(42)), Atspi.Role.get_name(Atspi.Role(42)))
    PUSH_BUTTON = (hash(Atspi.Role(43)), Atspi.Role.get_name(Atspi.Role(43)))
    RADIO_BUTTON = (hash(Atspi.Role(44)), Atspi.Role.get_name(Atspi.Role(44)))
    RADIO_MENU_ITEM = (hash(Atspi.Role(45)), Atspi.Role.get_name(Atspi.Role(45)))
    ROOT_PANE = (hash(Atspi.Role(46)), Atspi.Role.get_name(Atspi.Role(46)))
    ROW_HEADER = (hash(Atspi.Role(47)), Atspi.Role.get_name(Atspi.Role(47)))
    SCROLL_BAR = (hash(Atspi.Role(48)), Atspi.Role.get_name(Atspi.Role(48)))
    SCROLL_PANE = (hash(Atspi.Role(49)), Atspi.Role.get_name(Atspi.Role(49)))

    SEPARATOR = (hash(Atspi.Role(50)), Atspi.Role.get_name(Atspi.Role(50)))
    SLIDER = (hash(Atspi.Role(51)), Atspi.Role.get_name(Atspi.Role(51)))
    SPIN_BUTTON = (hash(Atspi.Role(52)), Atspi.Role.get_name(Atspi.Role(52)))
    SPLIT_PANE = (hash(Atspi.Role(53)), Atspi.Role.get_name(Atspi.Role(53)))
    STATUS_BAR = (hash(Atspi.Role(54)), Atspi.Role.get_name(Atspi.Role(54)))
    TABLE = (hash(Atspi.Role(55)), Atspi.Role.get_name(Atspi.Role(55)))
    TABLE_CELL = (hash(Atspi.Role(56)), Atspi.Role.get_name(Atspi.Role(56)))
    TABLE_COLUMN_HEADER = (hash(Atspi.Role(57)), Atspi.Role.get_name(Atspi.Role(57)))
    TABLE_ROW_HEADER = (hash(Atspi.Role(58)), Atspi.Role.get_name(Atspi.Role(58)))
    TEAROFF_MENU_ITEM = (hash(Atspi.Role(59)), Atspi.Role.get_name(Atspi.Role(59)))

    TERMINAL = (hash(Atspi.Role(60)), Atspi.Role.get_name(Atspi.Role(60)))
    TEXT = (hash(Atspi.Role(61)), Atspi.Role.get_name(Atspi.Role(61)))
    TOGGLE_BUTTON = (hash(Atspi.Role(62)), Atspi.Role.get_name(Atspi.Role(62)))
    TOOL_BAR = (hash(Atspi.Role(63)), Atspi.Role.get_name(Atspi.Role(63)))
    TOOL_TIP = (hash(Atspi.Role(64)), Atspi.Role.get_name(Atspi.Role(64)))
    TREE = (hash(Atspi.Role(65)), Atspi.Role.get_name(Atspi.Role(65)))
    TREE_TABLE = (hash(Atspi.Role(66)), Atspi.Role.get_name(Atspi.Role(66)))
    UNKNOWN = (hash(Atspi.Role(67)), Atspi.Role.get_name(Atspi.Role(67)))
    VIEWPORT = (hash(Atspi.Role(68)), Atspi.Role.get_name(Atspi.Role(68)))
    WINDOW = (hash(Atspi.Role(69)), Atspi.Role.get_name(Atspi.Role(69)))

    EXTENDED = (hash(Atspi.Role(70)), Atspi.Role.get_name(Atspi.Role(70)))
    HEADER = (hash(Atspi.Role(71)), Atspi.Role.get_name(Atspi.Role(71)))
    FOOTER = (hash(Atspi.Role(72)), Atspi.Role.get_name(Atspi.Role(72)))
    PARAGRAPH = (hash(Atspi.Role(73)), Atspi.Role.get_name(Atspi.Role(73)))
    RULER = (hash(Atspi.Role(74)), Atspi.Role.get_name(Atspi.Role(74)))
    APPLICATION = (hash(Atspi.Role(75)), Atspi.Role.get_name(Atspi.Role(75)))
    AUTOCOMPLETE = (hash(Atspi.Role(76)), Atspi.Role.get_name(Atspi.Role(76)))
    EDITBAR = (hash(Atspi.Role(77)), Atspi.Role.get_name(Atspi.Role(77)))
    EMBEDDED = (hash(Atspi.Role(78)), Atspi.Role.get_name(Atspi.Role(78)))
    ENTRY = (hash(Atspi.Role(79)), Atspi.Role.get_name(Atspi.Role(79)))

    CHART = (hash(Atspi.Role(80)), Atspi.Role.get_name(Atspi.Role(80)))
    CAPTION = (hash(Atspi.Role(81)), Atspi.Role.get_name(Atspi.Role(81)))
    DOCUMENT_FRAME = (hash(Atspi.Role(82)), Atspi.Role.get_name(Atspi.Role(82)))
    HEADING = (hash(Atspi.Role(83)), Atspi.Role.get_name(Atspi.Role(83)))
    PAGE = (hash(Atspi.Role(84)), Atspi.Role.get_name(Atspi.Role(84)))
    SECTION = (hash(Atspi.Role(85)), Atspi.Role.get_name(Atspi.Role(85)))
    REDUNDANT_OBJECT = (hash(Atspi.Role(86)), Atspi.Role.get_name(Atspi.Role(86)))
    FORM = (hash(Atspi.Role(87)), Atspi.Role.get_name(Atspi.Role(87)))
    LINK = (hash(Atspi.Role(88)), Atspi.Role.get_name(Atspi.Role(88)))
    INPUT_METHOD_WINDOW = (hash(Atspi.Role(89)), Atspi.Role.get_name(Atspi.Role(89)))

    TABLE_ROW = (hash(Atspi.Role(90)), Atspi.Role.get_name(Atspi.Role(90)))
    TREE_ITEM = (hash(Atspi.Role(91)), Atspi.Role.get_name(Atspi.Role(91)))
    DOCUMENT_SPREADSHEET = (hash(Atspi.Role(92)), Atspi.Role.get_name(Atspi.Role(92)))
    DOCUMENT_PRESENTATION = (hash(Atspi.Role(93)), Atspi.Role.get_name(Atspi.Role(93)))
    DOCUMENT_TEXT = (hash(Atspi.Role(94)), Atspi.Role.get_name(Atspi.Role(94)))
    DOCUMENT_WEB = (hash(Atspi.Role(95)), Atspi.Role.get_name(Atspi.Role(95)))
    DOCUMENT_EMAIL = (hash(Atspi.Role(96)), Atspi.Role.get_name(Atspi.Role(96)))
    COMMENT = (hash(Atspi.Role(97)), Atspi.Role.get_name(Atspi.Role(97)))
    LIST_BOX = (hash(Atspi.Role(98)), Atspi.Role.get_name(Atspi.Role(98)))
    GROUPING = (hash(Atspi.Role(99)), Atspi.Role.get_name(Atspi.Role(99)))

    IMAGE_MAP = (hash(Atspi.Role(100)), Atspi.Role.get_name(Atspi.Role(100)))
    NOTIFICATION = (hash(Atspi.Role(101)), Atspi.Role.get_name(Atspi.Role(101)))
    INFO_BAR = (hash(Atspi.Role(102)), Atspi.Role.get_name(Atspi.Role(102)))
    LEVEL_BAR = (hash(Atspi.Role(103)), Atspi.Role.get_name(Atspi.Role(103)))
    TITLE_BAR = (hash(Atspi.Role(104)), Atspi.Role.get_name(Atspi.Role(104)))
    BLOCK_QUOTE = (hash(Atspi.Role(105)), Atspi.Role.get_name(Atspi.Role(105)))
    AUDIO = (hash(Atspi.Role(106)), Atspi.Role.get_name(Atspi.Role(106)))
    VIDEO = (hash(Atspi.Role(107)), Atspi.Role.get_name(Atspi.Role(107)))
    DEFINITION = (hash(Atspi.Role(108)), Atspi.Role.get_name(Atspi.Role(108)))
    ARTICLE = (hash(Atspi.Role(109)), Atspi.Role.get_name(Atspi.Role(109)))

    LANDMARK = (hash(Atspi.Role(110)), Atspi.Role.get_name(Atspi.Role(110)))
    LOG = (hash(Atspi.Role(111)), Atspi.Role.get_name(Atspi.Role(111)))
    MARQUEE = (hash(Atspi.Role(112)), Atspi.Role.get_name(Atspi.Role(112)))
    MATH = (hash(Atspi.Role(113)), Atspi.Role.get_name(Atspi.Role(113)))
    RATING = (hash(Atspi.Role(114)), Atspi.Role.get_name(Atspi.Role(114)))
    TIMER = (hash(Atspi.Role(115)), Atspi.Role.get_name(Atspi.Role(115)))
    STATIC = (hash(Atspi.Role(116)), Atspi.Role.get_name(Atspi.Role(116)))
    MATH_FRACTION = (hash(Atspi.Role(117)), Atspi.Role.get_name(Atspi.Role(117)))
    MATH_ROOT = (hash(Atspi.Role(118)), Atspi.Role.get_name(Atspi.Role(118)))
    SUBSCRIPT = (hash(Atspi.Role(119)), Atspi.Role.get_name(Atspi.Role(119)))

    SUPERSCRIPT = (hash(Atspi.Role(120)), Atspi.Role.get_name(Atspi.Role(120)))
    DESCRIPTION_LIST = (hash(Atspi.Role(121)), Atspi.Role.get_name(Atspi.Role(121)))
    DESCRIPTION_TERM = (hash(Atspi.Role(122)), Atspi.Role.get_name(Atspi.Role(122)))
    DESCRIPTION_VALUE = (hash(Atspi.Role(123)), Atspi.Role.get_name(Atspi.Role(123)))
    FOOTNOTE = (hash(Atspi.Role(124)), Atspi.Role.get_name(Atspi.Role(124)))
    CONTENT_DELETION = (hash(Atspi.Role(125)), Atspi.Role.get_name(Atspi.Role(125)))
    CONTENT_INSERTION = (hash(Atspi.Role(126)), Atspi.Role.get_name(Atspi.Role(126)))
    MARK = (hash(Atspi.Role(127)), Atspi.Role.get_name(Atspi.Role(127)))
    SUGGESTION = (hash(Atspi.Role(128)), Atspi.Role.get_name(Atspi.Role(128)))
    LAST_DEFINED = (hash(Atspi.Role(129)), Atspi.Role.get_name(Atspi.Role(129)))